version: "3"
services:
  redis:
    image: redis
    ports:
      - "${DOCKER_COMPOSE_REDIS_PORT}:6379"
    networks:
      - backend
  postgres:
    image: postgres
    ports:
      - "${DOCKER_COMPOSE_POSTGRES_PORT}:5432"
    volumes:
      - ./bootstrap/postgres/init:/docker-entrypoint-initdb.d
      - ./bootstrap/postgres/data:/var/lib/postgresql/data
    networks:
      - backend
  inspectr-backend:
    image: inspectr-backend:v001
    command: sh -c "reflex -c reflex.conf"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${DOCKER_COMPOSE_BACKEND_PORT}:3000"
    volumes:
      - .:/go/src/github.com/inspectr/backend
    depends_on:
      - postgres
      - redis
    networks:
      - backend
networks:
  backend:
    driver: bridge
