---
environment: "development"
redis:
  username:
  password:
  server: "redis:6379"
  database: "0"
  pool: "30"
  process: "inspectr"
plugins:
  api:
    workers: 1
    oidc_uri: 
    oidc_client_id: 
    postgres:
      host: "postgres"
      port: "5432"
      user: "postgres"
      dbname: "inspectr"
      sslmode: "disable"
      password: ""
    service_address: ":3000"
  heartbeat:
    workers: 0
  sqs:
    workers: 1
    aws_access_key_id: "AKIAJHNGWC6ZQ4E4IIWQ"
    aws_secret_access_key: "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"
    aws_sqs_url: "https://sqs.us-east-1.amazonaws.com/927411751048/inspectr.fifo"
    aws_region: "us-east-1"
